<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>DiffHarness</RootNamespace>
    <AssemblyName Condition="'$(EdrRead)' == 'true'">DiffHarnessEDR</AssemblyName>
    <AssemblyName Condition="'$(EdrRead)' != 'true'">DiffHarness</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath Condition="'$(EdrRead)' == 'true'">bin\Release-EDR\</OutputPath>
    <OutputPath Condition="'$(EdrRead)' != 'true'">bin\Release\</OutputPath>
    <DefineConstants Condition="'$(EdrRead)' != 'true'">$(DefineConstants);NPOI_READ</DefineConstants>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ExcelDiff\ExcelDiff.csproj" />
  </ItemGroup>
</Project>
