# refresh_state.ps1 - Regenerate AI_Programmer\PROJECT_STATE.md from live git state.
#
# Single source of truth for "which branch / commit am I on, what is uncommitted".
# Hand-editing of PROJECT_STATE.md is pointless: this script overwrites it.
#
# Usage:  powershell -ExecutionPolicy Bypass -File AI_Script\refresh_state.ps1
#
# NOTE: keep this file pure ASCII (PowerShell 5.1 reads .ps1 without BOM as ANSI).
#       The output is written as UTF-8 (no BOM) to avoid the ANSI-corruption pitfall
#       (INVARIANTS D3).

$ErrorActionPreference = 'Stop'

# git.exe emits UTF-8; tell PowerShell to decode native output as UTF-8
# (otherwise commit authors/messages with non-ASCII become mojibake).
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

$scriptDir = $PSScriptRoot                 # ...\AI_Script
$root      = Split-Path -Parent $scriptDir # repo root
$out       = Join-Path $root 'AI_Programmer\PROJECT_STATE.md'

function Invoke-Git([string[]]$cmdArgs) {
    return (& git.exe -C $root @cmdArgs 2>&1 | Out-String).Trim()
}

$branch   = Invoke-Git @('rev-parse', '--abbrev-ref', 'HEAD')
$head     = Invoke-Git @('rev-parse', 'HEAD')
$subject  = Invoke-Git @('log', '-1', '--format=%h %s%nAuthor: %an <%ae>%nDate:   %ad', '--date=short')
$recent   = Invoke-Git @('log', '--oneline', '-10', '--decorate')
$upstream = Invoke-Git @('rev-parse', '--abbrev-ref', '--symbolic-full-name', '@{u}')
if ($LASTEXITCODE -ne 0) { $upstream = '(no upstream)' }

$statusRaw = & git -C $root status --short 2>&1 | Out-String
if ([string]::IsNullOrWhiteSpace($statusRaw)) { $status = '(working tree clean)' }
else { $status = $statusRaw.Trim() }

$ts = (Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz')

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# PROJECT_STATE - project and git version state (single source of truth)')
$lines.Add('')
$lines.Add('> Auto-generated by `AI_Script\refresh_state.ps1`. Do NOT hand-edit.')
$lines.Add('> Refresh: `powershell -ExecutionPolicy Bypass -File AI_Script\refresh_state.ps1`')
$lines.Add('> Generated: ' + $ts)
$lines.Add('')
$lines.Add('## Branch / upstream')
$lines.Add('- Branch:   `' + $branch + '`')
$lines.Add('- Upstream: `' + $upstream + '`')
$lines.Add('- HEAD:     `' + $head + '`')
$lines.Add('')
$lines.Add('## HEAD commit')
$lines.Add('```')
$lines.Add($subject)
$lines.Add('```')
$lines.Add('')
$lines.Add('## Recent commits')
$lines.Add('```')
$lines.Add($recent)
$lines.Add('```')
$lines.Add('')
$lines.Add('## Uncommitted changes (working tree vs HEAD)')
$lines.Add('```')
$lines.Add($status)
$lines.Add('```')
$lines.Add('')

$content = $lines -join "`r`n"

# UTF-8 without BOM: same convention as lang\*.json (INVARIANTS D3).
$utf8 = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($out, $content, $utf8)

Write-Host ('Wrote ' + $out)
