//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelDiff.GUI.Properties {
    using System;
    using ExcelDiff.GUI.Localization;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelDiff.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Diff.
        /// </summary>
        public static string Button_ExtractDiff {
            get {
                return LocalizationManager.GetString("Button_ExtractDiff", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Log.
        /// </summary>
        public static string ContextMenu_BuildCellBaseLog {
            get {
                return LocalizationManager.GetString("ContextMenu_BuildCellBaseLog", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Column Base Log.
        /// </summary>
        public static string ContextMenu_BuildColumnBaseLog {
            get {
                return LocalizationManager.GetString("ContextMenu_BuildColumnBaseLog", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Row Base Log.
        /// </summary>
        public static string ContextMenu_BuildRowBaseLog {
            get {
                return LocalizationManager.GetString("ContextMenu_BuildRowBaseLog", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as CSV.
        /// </summary>
        public static string ContextMenu_CopyAsCsv {
            get {
                return LocalizationManager.GetString("ContextMenu_CopyAsCsv", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as TSV.
        /// </summary>
        public static string ContextMenu_CopyAsTsv {
            get {
                return LocalizationManager.GetString("ContextMenu_CopyAsTsv", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract diff with this row as column header..
        /// </summary>
        public static string ContextMenu_DiffAsHeader {
            get {
                return LocalizationManager.GetString("ContextMenu_DiffAsHeader", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↑Reset Column Header.
        /// </summary>
        public static string ContextMenu_ResetColumnHeader {
            get {
                return LocalizationManager.GetString("ContextMenu_ResetColumnHeader", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ←Reset Row Header.
        /// </summary>
        public static string ContextMenu_ResetRowHeader {
            get {
                return LocalizationManager.GetString("ContextMenu_ResetRowHeader", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↑Set Column Header.
        /// </summary>
        public static string ContextMenu_SetColumnHeader {
            get {
                return LocalizationManager.GetString("ContextMenu_SetColumnHeader", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ←Set Row Header.
        /// </summary>
        public static string ContextMenu_SetRowHeader {
            get {
                return LocalizationManager.GetString("ContextMenu_SetRowHeader", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${LEFT} → ${RIGHT}.
        /// </summary>
        public static string DefaultColumnBaseLogFormat {
            get {
                return LocalizationManager.GetString("DefaultColumnBaseLogFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed &quot;${ROW}&quot;&apos;s &quot;${COL}&quot; to &quot;${RIGHT}&quot; from &quot;${LEFT}&quot;.
        /// </summary>
        public static string DefaultLogFormat {
            get {
                return LocalizationManager.GetString("DefaultLogFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;${ROW}&quot; was added..
        /// </summary>
        public static string DefaultLogFormatAddedRow {
            get {
                return LocalizationManager.GetString("DefaultLogFormatAddedRow", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;${ROW}&quot; was removed..
        /// </summary>
        public static string DefaultLogFormatRemovedRow {
            get {
                return LocalizationManager.GetString("DefaultLogFormatRemovedRow", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${LEFT} → ${RIGHT}.
        /// </summary>
        public static string DefaultRowBaseLogFormat {
            get {
                return LocalizationManager.GetString("DefaultRowBaseLogFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        public static string GroupBox_Behavior {
            get {
                return LocalizationManager.GetString("GroupBox_Behavior", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Format.
        /// </summary>
        public static string GroupBox_DisplayFormat {
            get {
                return LocalizationManager.GetString("GroupBox_DisplayFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Format.
        /// </summary>
        public static string GroupBox_LogFormat {
            get {
                return LocalizationManager.GetString("GroupBox_LogFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Setting.
        /// </summary>
        public static string GroupBox_ReadSetting {
            get {
                return LocalizationManager.GetString("GroupBox_ReadSetting", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string GroupBox_Style {
            get {
                return LocalizationManager.GetString("GroupBox_Style", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Color.
        /// </summary>
        public static string Label_AddedColor {
            get {
                return LocalizationManager.GetString("Label_AddedColor", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Row Log Format.
        /// </summary>
        public static string Label_AddedRowLogFormat {
            get {
                return LocalizationManager.GetString("Label_AddedRowLogFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Rows({0}).
        /// </summary>
        public static string Label_AddedRows {
            get {
                return LocalizationManager.GetString("Label_AddedRows", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always expand cell diff.
        /// </summary>
        public static string Label_AlwaysExpandCellDiff {
            get {
                return LocalizationManager.GetString("Label_AlwaysExpandCellDiff", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Modified Row.
        /// </summary>
        public static string Label_ColorModifiedRow {
            get {
                return LocalizationManager.GetString("Label_ColorModifiedRow", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Base Log Format.
        /// </summary>
        public static string Label_ColumnBaseLogFormat {
            get {
                return LocalizationManager.GetString("Label_ColumnBaseLogFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Header Color.
        /// </summary>
        public static string Label_ColumnHeaderColor {
            get {
                return LocalizationManager.GetString("Label_ColumnHeaderColor", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Width.
        /// </summary>
        public static string Label_ColumnWidth {
            get {
                return LocalizationManager.GetString("Label_ColumnWidth", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Cell Height.
        /// </summary>
        public static string Label_FitRowHeight {
            get {
                return LocalizationManager.GetString("Label_FitRowHeight", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus first diff when extracted.
        /// </summary>
        public static string Label_FocusFirstDiff {
            get {
                return LocalizationManager.GetString("Label_FocusFirstDiff", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore File Setting.
        /// </summary>
        public static string Label_IgnoreFileSetting {
            get {
                return LocalizationManager.GetString("Label_IgnoreFileSetting", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Cell Log Format.
        /// </summary>
        public static string Label_LogFormat {
            get {
                return LocalizationManager.GetString("Label_LogFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Row Height.
        /// </summary>
        public static string Label_MaxRowHeight {
            get {
                return LocalizationManager.GetString("Label_MaxRowHeight", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Row Height.
        /// </summary>
        public static string Label_MinRowHeight {
            get {
                return LocalizationManager.GetString("Label_MinRowHeight", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Cells({0}).
        /// </summary>
        public static string Label_ModifiedCells {
            get {
                return LocalizationManager.GetString("Label_ModifiedCells", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Color.
        /// </summary>
        public static string Label_ModifiedColor {
            get {
                return LocalizationManager.GetString("Label_ModifiedColor", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Row Color.
        /// </summary>
        public static string Label_ModifiedRowColor {
            get {
                return LocalizationManager.GetString("Label_ModifiedRowColor", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Rows({0}).
        /// </summary>
        public static string Label_ModifiedRows {
            get {
                return LocalizationManager.GetString("Label_ModifiedRows", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show dialog if no diff.
        /// </summary>
        public static string Label_NotifyEqual {
            get {
                return LocalizationManager.GetString("Label_NotifyEqual", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Color.
        /// </summary>
        public static string Label_RemovedColor {
            get {
                return LocalizationManager.GetString("Label_RemovedColor", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Row Log Format.
        /// </summary>
        public static string Label_RemovedRowLogFormat {
            get {
                return LocalizationManager.GetString("Label_RemovedRowLogFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Rows({0}).
        /// </summary>
        public static string Label_RemovedRows {
            get {
                return LocalizationManager.GetString("Label_RemovedRows", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Base Log Format.
        /// </summary>
        public static string Label_RowBaseLogFormat {
            get {
                return LocalizationManager.GetString("Label_RowBaseLogFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Colors.
        /// </summary>
        public static string Label_RowColor {
            get {
                return LocalizationManager.GetString("Label_RowColor", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Header Color.
        /// </summary>
        public static string Label_RowHeaderColor {
            get {
                return LocalizationManager.GetString("Label_RowHeaderColor", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Height.
        /// </summary>
        public static string Label_RowlHeight {
            get {
                return LocalizationManager.GetString("Label_RowlHeight", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip first blank columns.
        /// </summary>
        public static string Label_SkipFirstBlankColumns {
            get {
                return LocalizationManager.GetString("Label_SkipFirstBlankColumns", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip first blank rows.
        /// </summary>
        public static string Label_SkipFirstBlankRows {
            get {
                return LocalizationManager.GetString("Label_SkipFirstBlankRows", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim last blank columns.
        /// </summary>
        public static string Label_TrimLastBlankColumns {
            get {
                return LocalizationManager.GetString("Label_TrimLastBlankColumns", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim last blank rows.
        /// </summary>
        public static string Label_TrimLastBlankRows {
            get {
                return LocalizationManager.GetString("Label_TrimLastBlankRows", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string MenuItem_Console {
            get {
                return LocalizationManager.GetString("MenuItem_Console", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute external command.
        /// </summary>
        public static string MenuItem_ExeExternalCmd {
            get {
                return LocalizationManager.GetString("MenuItem_ExeExternalCmd", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Commands.
        /// </summary>
        public static string MenuItem_ExternalCommands {
            get {
                return LocalizationManager.GetString("MenuItem_ExternalCommands", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Settings.
        /// </summary>
        public static string MenuItem_FileSettings {
            get {
                return LocalizationManager.GetString("MenuItem_FileSettings", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Setting.
        /// </summary>
        public static string MenuItem_GeneralSetting {
            get {
                return LocalizationManager.GetString("MenuItem_GeneralSetting", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open as Dst File.
        /// </summary>
        public static string MenuItem_OpenAsDstFile {
            get {
                return LocalizationManager.GetString("MenuItem_OpenAsDstFile", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open as Src File.
        /// </summary>
        public static string MenuItem_OpenAsSrcFile {
            get {
                return LocalizationManager.GetString("MenuItem_OpenAsSrcFile", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open dst File.
        /// </summary>
        public static string MenuItem_OpenDstFile {
            get {
                return LocalizationManager.GetString("MenuItem_OpenDstFile", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open src file.
        /// </summary>
        public static string MenuItem_OpenSrcFile {
            get {
                return LocalizationManager.GetString("MenuItem_OpenSrcFile", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        public static string MenuItem_RecentFiles {
            get {
                return LocalizationManager.GetString("MenuItem_RecentFiles", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent File Sets.
        /// </summary>
        public static string MenuItem_RecentFileSets {
            get {
                return LocalizationManager.GetString("MenuItem_RecentFileSets", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MenuItem_View {
            get {
                return LocalizationManager.GetString("MenuItem_View", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no difference..
        /// </summary>
        public static string Message_NoDiff {
            get {
                return LocalizationManager.GetString("Message_NoDiff", ResourceManager, resourceCulture);
            }
        }
        
        public static string Message_NoDiffFormat {
            get {
                return LocalizationManager.GetString("Message_NoDiffFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart to apply the changes..
        /// </summary>
        public static string Message_Reboot {
            get {
                return LocalizationManager.GetString("Message_Reboot", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting Diff ....
        /// </summary>
        public static string Msg_ExtractingDiff {
            get {
                return LocalizationManager.GetString("Msg_ExtractingDiff", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet index of the applied file settings is out of range.
        ///Will use first sheet.
        ///If you don&apos;t want to apply file settings, enable &quot;Ignore File Setting&quot;.
        /// </summary>
        public static string Msg_OutofSheetRange {
            get {
                return LocalizationManager.GetString("Msg_OutofSheetRange", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Files ....
        /// </summary>
        public static string Msg_ReadingFiles {
            get {
                return LocalizationManager.GetString("Msg_ReadingFiles", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not be displayed.
        /// </summary>
        public static string Msg_Undisplayable {
            get {
                return LocalizationManager.GetString("Msg_Undisplayable", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many records. Display only around diff..
        /// </summary>
        public static string Msg_WarnSize {
            get {
                return LocalizationManager.GetString("Msg_WarnSize", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string RadioButton_ShowAll {
            get {
                return LocalizationManager.GetString("RadioButton_ShowAll", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Diff.
        /// </summary>
        public static string RadioButton_ShowOnlyDiff {
            get {
                return LocalizationManager.GetString("RadioButton_ShowOnlyDiff", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Down.
        /// </summary>
        public static string Shortcut_Ctrl_Down {
            get {
                return LocalizationManager.GetString("Shortcut_Ctrl_Down", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + I.
        /// </summary>
        public static string Shortcut_Ctrl_I {
            get {
                return LocalizationManager.GetString("Shortcut_Ctrl_I", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + K.
        /// </summary>
        public static string Shortcut_Ctrl_K {
            get {
                return LocalizationManager.GetString("Shortcut_Ctrl_K", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + L.
        /// </summary>
        public static string Shortcut_Ctrl_L {
            get {
                return LocalizationManager.GetString("Shortcut_Ctrl_L", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Left.
        /// </summary>
        public static string Shortcut_Ctrl_Left {
            get {
                return LocalizationManager.GetString("Shortcut_Ctrl_Left", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + O.
        /// </summary>
        public static string Shortcut_Ctrl_O {
            get {
                return LocalizationManager.GetString("Shortcut_Ctrl_O", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Right.
        /// </summary>
        public static string Shortcut_Ctrl_Right {
            get {
                return LocalizationManager.GetString("Shortcut_Ctrl_Right", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Up.
        /// </summary>
        public static string Shortcut_Ctrl_Up {
            get {
                return LocalizationManager.GetString("Shortcut_Ctrl_Up", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F8.
        /// </summary>
        public static string Shortcut_F8 {
            get {
                return LocalizationManager.GetString("Shortcut_F8", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F9.
        /// </summary>
        public static string Shortcut_F9 {
            get {
                return LocalizationManager.GetString("Shortcut_F9", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit External Command.
        /// </summary>
        public static string Title_ExternalCommandEditorWindow {
            get {
                return LocalizationManager.GetString("Title_ExternalCommandEditorWindow", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Commands.
        /// </summary>
        public static string Title_ExternalCommandsWindow {
            get {
                return LocalizationManager.GetString("Title_ExternalCommandsWindow", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit File Setting.
        /// </summary>
        public static string Title_FileSettingEditorWindow {
            get {
                return LocalizationManager.GetString("Title_FileSettingEditorWindow", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Settings.
        /// </summary>
        public static string Title_FileSettingsWindow {
            get {
                return LocalizationManager.GetString("Title_FileSettingsWindow", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string Title_GeneralSettingWindow {
            get {
                return LocalizationManager.GetString("Title_GeneralSettingWindow", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dst File Path.
        /// </summary>
        public static string ToolTip_DstFilePath {
            get {
                return LocalizationManager.GetString("ToolTip_DstFilePath", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dst Sheet.
        /// </summary>
        public static string ToolTip_DstSheet {
            get {
                return LocalizationManager.GetString("ToolTip_DstSheet", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Src File Path.
        /// </summary>
        public static string ToolTip_SrcFilePath {
            get {
                return LocalizationManager.GetString("ToolTip_SrcFilePath", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Src Sheet.
        /// </summary>
        public static string ToolTip_SrcSheet {
            get {
                return LocalizationManager.GetString("ToolTip_SrcSheet", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap src and dst.
        /// </summary>
        public static string ToolTip_Swap {
            get {
                return LocalizationManager.GetString("ToolTip_Swap", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Word_Apply {
            get {
                return LocalizationManager.GetString("Word_Apply", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Args.
        /// </summary>
        public static string Word_Args {
            get {
                return LocalizationManager.GetString("Word_Args", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank.
        /// </summary>
        public static string Word_Blank {
            get {
                return LocalizationManager.GetString("Word_Blank", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Word_Cancel {
            get {
                return LocalizationManager.GetString("Word_Cancel", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaseSensitive.
        /// </summary>
        public static string Word_CaseSensitive {
            get {
                return LocalizationManager.GetString("Word_CaseSensitive", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Header Index.
        /// </summary>
        public static string Word_ColumnHeaderIndex {
            get {
                return LocalizationManager.GetString("Word_ColumnHeaderIndex", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Word_Default {
            get {
                return LocalizationManager.GetString("Word_Default", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Word_Done {
            get {
                return LocalizationManager.GetString("Word_Done", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dst File.
        /// </summary>
        public static string Word_DstFile {
            get {
                return LocalizationManager.GetString("Word_DstFile", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Word_Edit {
            get {
                return LocalizationManager.GetString("Word_Edit", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Word_English {
            get {
                return LocalizationManager.GetString("Word_English", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExactMatch.
        /// </summary>
        public static string Word_ExactMatch {
            get {
                return LocalizationManager.GetString("Word_ExactMatch", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable.
        /// </summary>
        public static string Word_Executable {
            get {
                return LocalizationManager.GetString("Word_Executable", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Word_File {
            get {
                return LocalizationManager.GetString("Word_File", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Word_Font {
            get {
                return LocalizationManager.GetString("Word_Font", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Word_Japanese {
            get {
                return LocalizationManager.GetString("Word_Japanese", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launguage.
        /// </summary>
        public static string Word_Language {
            get {
                return LocalizationManager.GetString("Word_Language", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Type.
        /// </summary>
        public static string Word_MatchType {
            get {
                return LocalizationManager.GetString("Word_MatchType", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Row Header Width.
        /// </summary>
        public static string Word_MaxRowHeaderWidth {
            get {
                return LocalizationManager.GetString("Word_MaxRowHeaderWidth", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Word_Name {
            get {
                return LocalizationManager.GetString("Word_Name", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Word_Path {
            get {
                return LocalizationManager.GetString("Word_Path", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex.
        /// </summary>
        public static string Word_Regex {
            get {
                return LocalizationManager.GetString("Word_Regex", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Word_Remove {
            get {
                return LocalizationManager.GetString("Word_Remove", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Word_Reset {
            get {
                return LocalizationManager.GetString("Word_Reset", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Header Index.
        /// </summary>
        public static string Word_RowHeaderIndex {
            get {
                return LocalizationManager.GetString("Word_RowHeaderIndex", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Header Name.
        /// </summary>
        public static string Word_RowHeaderName {
            get {
                return LocalizationManager.GetString("Word_RowHeaderName", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Word_Search {
            get {
                return LocalizationManager.GetString("Word_Search", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Word_Setting {
            get {
                return LocalizationManager.GetString("Word_Setting", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet.
        /// </summary>
        public static string Word_Sheet {
            get {
                return LocalizationManager.GetString("Word_Sheet", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Index.
        /// </summary>
        public static string Word_SheetIndex {
            get {
                return LocalizationManager.GetString("Word_SheetIndex", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string Word_SheetName {
            get {
                return LocalizationManager.GetString("Word_SheetName", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Src File.
        /// </summary>
        public static string Word_SrcFile {
            get {
                return LocalizationManager.GetString("Word_SrcFile", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Startup Sheet.
        /// </summary>
        public static string Word_StartupSheet {
            get {
                return LocalizationManager.GetString("Word_StartupSheet", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        public static string Word_Tool {
            get {
                return LocalizationManager.GetString("Word_Tool", ResourceManager, resourceCulture);
            }
        }
        
        public static string Word_System {
            get {
                return LocalizationManager.GetString("Word_System", ResourceManager, resourceCulture);
            }
        }
        
        public static string Label_StartOnBoot {
            get {
                return LocalizationManager.GetString("Label_StartOnBoot", ResourceManager, resourceCulture);
            }
        }
        
        public static string Label_RunInBackground {
            get {
                return LocalizationManager.GetString("Label_RunInBackground", ResourceManager, resourceCulture);
            }
        }
        
        public static string Word_Open {
            get {
                return LocalizationManager.GetString("Word_Open", ResourceManager, resourceCulture);
            }
        }
        
        public static string Word_Exit {
            get {
                return LocalizationManager.GetString("Word_Exit", ResourceManager, resourceCulture);
            }
        }
        
        public static string Word_OK {
            get {
                return LocalizationManager.GetString("Word_OK", ResourceManager, resourceCulture);
            }
        }
        
        public static string Word_Close {
            get {
                return LocalizationManager.GetString("Word_Close", ResourceManager, resourceCulture);
            }
        }
    }
}
