//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelDiff.GUI.Properties {
    using System;
    using ExcelDiff.GUI.Localization;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelDiff.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Extract Diff に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_ExtractDiff {
            get {
                return LocalizationManager.GetString("Button_ExtractDiff", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_BuildCellBaseLog {
            get {
                return LocalizationManager.GetString("ContextMenu_BuildCellBaseLog", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Build Column Base Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_BuildColumnBaseLog {
            get {
                return LocalizationManager.GetString("ContextMenu_BuildColumnBaseLog", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Build Row Base Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_BuildRowBaseLog {
            get {
                return LocalizationManager.GetString("ContextMenu_BuildRowBaseLog", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy as CSV に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_CopyAsCsv {
            get {
                return LocalizationManager.GetString("ContextMenu_CopyAsCsv", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy as TSV に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_CopyAsTsv {
            get {
                return LocalizationManager.GetString("ContextMenu_CopyAsTsv", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract diff with this row as column header. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_DiffAsHeader {
            get {
                return LocalizationManager.GetString("ContextMenu_DiffAsHeader", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   ↑Reset Column Header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_ResetColumnHeader {
            get {
                return LocalizationManager.GetString("ContextMenu_ResetColumnHeader", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   ←Reset Row Header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_ResetRowHeader {
            get {
                return LocalizationManager.GetString("ContextMenu_ResetRowHeader", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   ↑Set Column Header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_SetColumnHeader {
            get {
                return LocalizationManager.GetString("ContextMenu_SetColumnHeader", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   ←Set Row Header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_SetRowHeader {
            get {
                return LocalizationManager.GetString("ContextMenu_SetRowHeader", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   ${LEFT} → ${RIGHT} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultColumnBaseLogFormat {
            get {
                return LocalizationManager.GetString("DefaultColumnBaseLogFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changed &quot;${ROW}&quot;&apos;s &quot;${COL}&quot; to &quot;${RIGHT}&quot; from &quot;${LEFT}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultLogFormat {
            get {
                return LocalizationManager.GetString("DefaultLogFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;${ROW}&quot; was added. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultLogFormatAddedRow {
            get {
                return LocalizationManager.GetString("DefaultLogFormatAddedRow", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;${ROW}&quot; was removed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultLogFormatRemovedRow {
            get {
                return LocalizationManager.GetString("DefaultLogFormatRemovedRow", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   ${LEFT} → ${RIGHT} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultRowBaseLogFormat {
            get {
                return LocalizationManager.GetString("DefaultRowBaseLogFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Behavior に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupBox_Behavior {
            get {
                return LocalizationManager.GetString("GroupBox_Behavior", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupBox_DisplayFormat {
            get {
                return LocalizationManager.GetString("GroupBox_DisplayFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupBox_LogFormat {
            get {
                return LocalizationManager.GetString("GroupBox_LogFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupBox_ReadSetting {
            get {
                return LocalizationManager.GetString("GroupBox_ReadSetting", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Style に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupBox_Style {
            get {
                return LocalizationManager.GetString("GroupBox_Style", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Added Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_AddedColor {
            get {
                return LocalizationManager.GetString("Label_AddedColor", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Added Row Log Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_AddedRowLogFormat {
            get {
                return LocalizationManager.GetString("Label_AddedRowLogFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Added Rows({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_AddedRows {
            get {
                return LocalizationManager.GetString("Label_AddedRows", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always expand cell diff に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_AlwaysExpandCellDiff {
            get {
                return LocalizationManager.GetString("Label_AlwaysExpandCellDiff", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color Modified Row に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ColorModifiedRow {
            get {
                return LocalizationManager.GetString("Label_ColorModifiedRow", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Base Log Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ColumnBaseLogFormat {
            get {
                return LocalizationManager.GetString("Label_ColumnBaseLogFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Header Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ColumnHeaderColor {
            get {
                return LocalizationManager.GetString("Label_ColumnHeaderColor", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ColumnWidth {
            get {
                return LocalizationManager.GetString("Label_ColumnWidth", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit Cell Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_FitRowHeight {
            get {
                return LocalizationManager.GetString("Label_FitRowHeight", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Focus first diff when extracted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_FocusFirstDiff {
            get {
                return LocalizationManager.GetString("Label_FocusFirstDiff", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore File Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_IgnoreFileSetting {
            get {
                return LocalizationManager.GetString("Label_IgnoreFileSetting", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Cell Log Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_LogFormat {
            get {
                return LocalizationManager.GetString("Label_LogFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Row Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_MaxRowHeight {
            get {
                return LocalizationManager.GetString("Label_MaxRowHeight", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min Row Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_MinRowHeight {
            get {
                return LocalizationManager.GetString("Label_MinRowHeight", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Cells({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ModifiedCells {
            get {
                return LocalizationManager.GetString("Label_ModifiedCells", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ModifiedColor {
            get {
                return LocalizationManager.GetString("Label_ModifiedColor", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Row Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ModifiedRowColor {
            get {
                return LocalizationManager.GetString("Label_ModifiedRowColor", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Rows({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ModifiedRows {
            get {
                return LocalizationManager.GetString("Label_ModifiedRows", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show dialog if no diff に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_NotifyEqual {
            get {
                return LocalizationManager.GetString("Label_NotifyEqual", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Removed Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_RemovedColor {
            get {
                return LocalizationManager.GetString("Label_RemovedColor", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Removed Row Log Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_RemovedRowLogFormat {
            get {
                return LocalizationManager.GetString("Label_RemovedRowLogFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Removed Rows({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_RemovedRows {
            get {
                return LocalizationManager.GetString("Label_RemovedRows", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Base Log Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_RowBaseLogFormat {
            get {
                return LocalizationManager.GetString("Label_RowBaseLogFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Colors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_RowColor {
            get {
                return LocalizationManager.GetString("Label_RowColor", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Header Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_RowHeaderColor {
            get {
                return LocalizationManager.GetString("Label_RowHeaderColor", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_RowlHeight {
            get {
                return LocalizationManager.GetString("Label_RowlHeight", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip first blank columns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_SkipFirstBlankColumns {
            get {
                return LocalizationManager.GetString("Label_SkipFirstBlankColumns", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip first blank rows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_SkipFirstBlankRows {
            get {
                return LocalizationManager.GetString("Label_SkipFirstBlankRows", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trim last blank columns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_TrimLastBlankColumns {
            get {
                return LocalizationManager.GetString("Label_TrimLastBlankColumns", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trim last blank rows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_TrimLastBlankRows {
            get {
                return LocalizationManager.GetString("Label_TrimLastBlankRows", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Console に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Console {
            get {
                return LocalizationManager.GetString("MenuItem_Console", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute external command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_ExeExternalCmd {
            get {
                return LocalizationManager.GetString("MenuItem_ExeExternalCmd", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   External Commands に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_ExternalCommands {
            get {
                return LocalizationManager.GetString("MenuItem_ExternalCommands", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_FileSettings {
            get {
                return LocalizationManager.GetString("MenuItem_FileSettings", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   General Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_GeneralSetting {
            get {
                return LocalizationManager.GetString("MenuItem_GeneralSetting", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open as Dst File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_OpenAsDstFile {
            get {
                return LocalizationManager.GetString("MenuItem_OpenAsDstFile", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open as Src File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_OpenAsSrcFile {
            get {
                return LocalizationManager.GetString("MenuItem_OpenAsSrcFile", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open dst File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_OpenDstFile {
            get {
                return LocalizationManager.GetString("MenuItem_OpenDstFile", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open src file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_OpenSrcFile {
            get {
                return LocalizationManager.GetString("MenuItem_OpenSrcFile", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_RecentFiles {
            get {
                return LocalizationManager.GetString("MenuItem_RecentFiles", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent File Sets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_RecentFileSets {
            get {
                return LocalizationManager.GetString("MenuItem_RecentFileSets", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_View {
            get {
                return LocalizationManager.GetString("MenuItem_View", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no difference. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NoDiff {
            get {
                return LocalizationManager.GetString("Message_NoDiff", ResourceManager, resourceCulture);
            }
        }
        
        public static string Message_NoDiffFormat {
            get {
                return LocalizationManager.GetString("Message_NoDiffFormat", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please restart to apply the changes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_Reboot {
            get {
                return LocalizationManager.GetString("Message_Reboot", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extracting Diff ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_ExtractingDiff {
            get {
                return LocalizationManager.GetString("Msg_ExtractingDiff", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sheet index of the applied file settings is out of range.
        ///Will use first sheet.
        ///If you don&apos;t want to apply file settings, enable &quot;Ignore File Setting&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_OutofSheetRange {
            get {
                return LocalizationManager.GetString("Msg_OutofSheetRange", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading Files ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_ReadingFiles {
            get {
                return LocalizationManager.GetString("Msg_ReadingFiles", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not be displayed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Undisplayable {
            get {
                return LocalizationManager.GetString("Msg_Undisplayable", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are too many records. Display only around diff. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_WarnSize {
            get {
                return LocalizationManager.GetString("Msg_WarnSize", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RadioButton_ShowAll {
            get {
                return LocalizationManager.GetString("RadioButton_ShowAll", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only Diff に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RadioButton_ShowOnlyDiff {
            get {
                return LocalizationManager.GetString("RadioButton_ShowOnlyDiff", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + Down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut_Ctrl_Down {
            get {
                return LocalizationManager.GetString("Shortcut_Ctrl_Down", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + I に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut_Ctrl_I {
            get {
                return LocalizationManager.GetString("Shortcut_Ctrl_I", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + K に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut_Ctrl_K {
            get {
                return LocalizationManager.GetString("Shortcut_Ctrl_K", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + L に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut_Ctrl_L {
            get {
                return LocalizationManager.GetString("Shortcut_Ctrl_L", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut_Ctrl_Left {
            get {
                return LocalizationManager.GetString("Shortcut_Ctrl_Left", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + O に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut_Ctrl_O {
            get {
                return LocalizationManager.GetString("Shortcut_Ctrl_O", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut_Ctrl_Right {
            get {
                return LocalizationManager.GetString("Shortcut_Ctrl_Right", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut_Ctrl_Up {
            get {
                return LocalizationManager.GetString("Shortcut_Ctrl_Up", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   F8 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut_F8 {
            get {
                return LocalizationManager.GetString("Shortcut_F8", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   F9 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut_F9 {
            get {
                return LocalizationManager.GetString("Shortcut_F9", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit External Command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_ExternalCommandEditorWindow {
            get {
                return LocalizationManager.GetString("Title_ExternalCommandEditorWindow", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   External Commands に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_ExternalCommandsWindow {
            get {
                return LocalizationManager.GetString("Title_ExternalCommandsWindow", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit File Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_FileSettingEditorWindow {
            get {
                return LocalizationManager.GetString("Title_FileSettingEditorWindow", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_FileSettingsWindow {
            get {
                return LocalizationManager.GetString("Title_FileSettingsWindow", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   General Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_GeneralSettingWindow {
            get {
                return LocalizationManager.GetString("Title_GeneralSettingWindow", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dst File Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_DstFilePath {
            get {
                return LocalizationManager.GetString("ToolTip_DstFilePath", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dst Sheet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_DstSheet {
            get {
                return LocalizationManager.GetString("ToolTip_DstSheet", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Src File Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_SrcFilePath {
            get {
                return LocalizationManager.GetString("ToolTip_SrcFilePath", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Src Sheet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_SrcSheet {
            get {
                return LocalizationManager.GetString("ToolTip_SrcSheet", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Swap src and dst に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_Swap {
            get {
                return LocalizationManager.GetString("ToolTip_Swap", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Apply {
            get {
                return LocalizationManager.GetString("Word_Apply", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Args に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Args {
            get {
                return LocalizationManager.GetString("Word_Args", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blank に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Blank {
            get {
                return LocalizationManager.GetString("Word_Blank", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Cancel {
            get {
                return LocalizationManager.GetString("Word_Cancel", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   CaseSensitive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_CaseSensitive {
            get {
                return LocalizationManager.GetString("Word_CaseSensitive", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Header Index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ColumnHeaderIndex {
            get {
                return LocalizationManager.GetString("Word_ColumnHeaderIndex", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Default {
            get {
                return LocalizationManager.GetString("Word_Default", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Done {
            get {
                return LocalizationManager.GetString("Word_Done", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dst File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_DstFile {
            get {
                return LocalizationManager.GetString("Word_DstFile", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Edit {
            get {
                return LocalizationManager.GetString("Word_Edit", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_English {
            get {
                return LocalizationManager.GetString("Word_English", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExactMatch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ExactMatch {
            get {
                return LocalizationManager.GetString("Word_ExactMatch", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Executable {
            get {
                return LocalizationManager.GetString("Word_Executable", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_File {
            get {
                return LocalizationManager.GetString("Word_File", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Font {
            get {
                return LocalizationManager.GetString("Word_Font", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Japanese {
            get {
                return LocalizationManager.GetString("Word_Japanese", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launguage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Language {
            get {
                return LocalizationManager.GetString("Word_Language", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_MatchType {
            get {
                return LocalizationManager.GetString("Word_MatchType", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Row Header Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_MaxRowHeaderWidth {
            get {
                return LocalizationManager.GetString("Word_MaxRowHeaderWidth", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Name {
            get {
                return LocalizationManager.GetString("Word_Name", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Path {
            get {
                return LocalizationManager.GetString("Word_Path", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regex に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Regex {
            get {
                return LocalizationManager.GetString("Word_Regex", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Remove {
            get {
                return LocalizationManager.GetString("Word_Remove", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Reset {
            get {
                return LocalizationManager.GetString("Word_Reset", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Header Index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_RowHeaderIndex {
            get {
                return LocalizationManager.GetString("Word_RowHeaderIndex", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Header Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_RowHeaderName {
            get {
                return LocalizationManager.GetString("Word_RowHeaderName", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Search {
            get {
                return LocalizationManager.GetString("Word_Search", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Setting {
            get {
                return LocalizationManager.GetString("Word_Setting", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sheet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Sheet {
            get {
                return LocalizationManager.GetString("Word_Sheet", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sheet Index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_SheetIndex {
            get {
                return LocalizationManager.GetString("Word_SheetIndex", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sheet Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_SheetName {
            get {
                return LocalizationManager.GetString("Word_SheetName", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Src File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_SrcFile {
            get {
                return LocalizationManager.GetString("Word_SrcFile", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set as Startup Sheet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_StartupSheet {
            get {
                return LocalizationManager.GetString("Word_StartupSheet", ResourceManager, resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Tool {
            get {
                return LocalizationManager.GetString("Word_Tool", ResourceManager, resourceCulture);
            }
        }
        
        public static string Word_System {
            get {
                return LocalizationManager.GetString("Word_System", ResourceManager, resourceCulture);
            }
        }
        
        public static string Label_StartOnBoot {
            get {
                return LocalizationManager.GetString("Label_StartOnBoot", ResourceManager, resourceCulture);
            }
        }
        
        public static string Label_RunInBackground {
            get {
                return LocalizationManager.GetString("Label_RunInBackground", ResourceManager, resourceCulture);
            }
        }
        
        public static string Word_Open {
            get {
                return LocalizationManager.GetString("Word_Open", ResourceManager, resourceCulture);
            }
        }
        
        public static string Word_Exit {
            get {
                return LocalizationManager.GetString("Word_Exit", ResourceManager, resourceCulture);
            }
        }
        
        public static string Word_OK {
            get {
                return LocalizationManager.GetString("Word_OK", ResourceManager, resourceCulture);
            }
        }
        
        public static string Word_Close {
            get {
                return LocalizationManager.GetString("Word_Close", ResourceManager, resourceCulture);
            }
        }
    }
}
